# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraint_file.xdc

# Block Designs: bd/Project_vDatamemory/Project_vDatamemory.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_vDatamemory || ORIG_REF_NAME==Project_vDatamemory} -quiet] -quiet

# IP: bd/Project_vDatamemory/ip/Project_vDatamemory_Datapath_IP_vDataMem_0_0/Project_vDatamemory_Datapath_IP_vDataMem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_vDatamemory_Datapath_IP_vDataMem_0_0 || ORIG_REF_NAME==Project_vDatamemory_Datapath_IP_vDataMem_0_0} -quiet] -quiet

# IP: bd/Project_vDatamemory/ip/Project_vDatamemory_processing_system7_0_0/Project_vDatamemory_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_vDatamemory_processing_system7_0_0 || ORIG_REF_NAME==Project_vDatamemory_processing_system7_0_0} -quiet] -quiet

# IP: bd/Project_vDatamemory/ip/Project_vDatamemory_axi_bram_ctrl_0_0/Project_vDatamemory_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_vDatamemory_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Project_vDatamemory_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Project_vDatamemory/ip/Project_vDatamemory_xbar_0/Project_vDatamemory_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_vDatamemory_xbar_0 || ORIG_REF_NAME==Project_vDatamemory_xbar_0} -quiet] -quiet

# IP: bd/Project_vDatamemory/ip/Project_vDatamemory_ps7_0_axi_periph_0/Project_vDatamemory_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_vDatamemory_ps7_0_axi_periph_0 || ORIG_REF_NAME==Project_vDatamemory_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Project_vDatamemory/ip/Project_vDatamemory_rst_ps7_0_100M_0/Project_vDatamemory_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_vDatamemory_rst_ps7_0_100M_0 || ORIG_REF_NAME==Project_vDatamemory_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Project_vDatamemory/ip/Project_vDatamemory_axi_bram_ctrl_0_bram_0/Project_vDatamemory_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_vDatamemory_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==Project_vDatamemory_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/Project_vDatamemory/ip/Project_vDatamemory_axi_gpio_0_0/Project_vDatamemory_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_vDatamemory_axi_gpio_0_0 || ORIG_REF_NAME==Project_vDatamemory_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Project_vDatamemory/ip/Project_vDatamemory_auto_pc_2/Project_vDatamemory_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_vDatamemory_auto_pc_2 || ORIG_REF_NAME==Project_vDatamemory_auto_pc_2} -quiet] -quiet

# IP: bd/Project_vDatamemory/ip/Project_vDatamemory_auto_pc_0/Project_vDatamemory_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_vDatamemory_auto_pc_0 || ORIG_REF_NAME==Project_vDatamemory_auto_pc_0} -quiet] -quiet

# IP: bd/Project_vDatamemory/ip/Project_vDatamemory_auto_pc_1/Project_vDatamemory_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_vDatamemory_auto_pc_1 || ORIG_REF_NAME==Project_vDatamemory_auto_pc_1} -quiet] -quiet

# XDC: bd/Project_vDatamemory/Project_vDatamemory_ooc.xdc
