# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/SFG/EE3007_Project_vDatamemory/EE3007_Project_vDatamemory.srcs/sources_1/bd/Project_vDatamemory/ip/Project_vDatamemory_xbar_0/Project_vDatamemory_xbar_0.xci
# IP: The module: 'Project_vDatamemory_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SFG/EE3007_Project_vDatamemory/EE3007_Project_vDatamemory.srcs/sources_1/bd/Project_vDatamemory/ip/Project_vDatamemory_xbar_0/Project_vDatamemory_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Project_vDatamemory_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/SFG/EE3007_Project_vDatamemory/EE3007_Project_vDatamemory.srcs/sources_1/bd/Project_vDatamemory/ip/Project_vDatamemory_xbar_0/Project_vDatamemory_xbar_0.xci
# IP: The module: 'Project_vDatamemory_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SFG/EE3007_Project_vDatamemory/EE3007_Project_vDatamemory.srcs/sources_1/bd/Project_vDatamemory/ip/Project_vDatamemory_xbar_0/Project_vDatamemory_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Project_vDatamemory_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
